issuer = ["https://dev-sk666r25.us.auth0.com/"]
algorithm = "RS256"
subject = "ZQ0LHZAloXxL51zNSMcQYQe01FLe02HN@clients"
jwks_url = "https://dev-sk666r25.us.auth0.com/.well-known/jwks.json"
allowed_scopes = { acls = "write", devices = "read" }
